version: '3.8'
services:
  app:
    image: lordrahl/grpc-contact
    container_name: contact-app
    ports:
      - 3500:3500
      - 3501:3501
      - 5200:5200
    environment:
      ENVIRONMENT: testing
    env_file:
      - ./.envs/.env

    depends_on:
      - postgres
    
    networks:
      - grpc-contact
  postgres:
    container_name: contact-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTRGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
      - APP_DB_USER=postgres
      - APP_DB_PASSWORD=password
      - APP_DB_NAME=postgres
    volumes:
      - "grpc-db-volume:/var/lib/postgresl/data"
    networks:
      - grpc-contact

  cockroachdb:
    container_name: roach
    image: cockroachdb/cockroach:latest
    ports:
      - 26257:26257
      - 8800:8080
    volumes:
      - "grpc-roach-volume:/cockroach/cockroach-data"
    networks:
      - grpc-contact
    command: start-single-node --insecure

  prometheus:
    image: prom/prometheus:latest
    container_name: grpc-contact-prom
    ports:
      - 9000:9090
    volumes:
      - .docker/prometheus:/etc/prometheus
      - prom-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - app
    networks:
      - grpc-contact

  grafana:
    image: grafana/grafana-enterprise
    container_name: grpc-grafana
    ports:
      - 3000:3000
    networks:
      - grpc-contact

volumes:
  grpc-db-volume:
    driver: local
  grpc-roach-volume:
    driver: local
  
  prom-data:
    driver: local

networks:
  grpc-contact:
    driver: bridge
  