version: '3.8'
services:
  postgres:
    container_name: contact-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTRGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
      - APP_DB_USER=postgres
      - APP_DB_PASSWORD=password
      - APP_DB_NAME=postgres
    volumes:
      - "grpc-db-volume:/var/lib/postgresl/data"
    networks:
      - grpc-contact

  cockroachdb:
    container_name: roach
    image: cockroachdb/cockroach:latest
    ports:
      - 26257:26257
      - 8800:8080
    volumes:
      - "grpc-roach-volume:/cockroach/cockroach-data"
    networks:
      - grpc-contact
    command: start-single-node --insecure

volumes:
  grpc-db-volume:
    driver: local
  grpc-roach-volume:
    driver: local

networks:
  grpc-contact:
    driver: bridge
  