name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Lint and Vet
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: make test
